name: Release from Develop

on:
  workflow_run:
    workflows: ["Maven Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Gerar nome da tag
        id: tagger
        run: |
          TAG_NAME="v1.0.$(date +'%Y%m%d%H%M%S')"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          git tag $TAG_NAME
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/francinemassaro/microcredit-platform.git $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
